"""Phase 2d final review: fixes for C1-C2, I1-I10 and the re-graded minors."""

import json
import subprocess
import sys
import time
from pathlib import Path

import pytest

from cairn.detectors.http import HttpDetector
from cairn.detectors.infra import InfraDetector
from cairn.discover.workspaces import workspace_packages
from cairn.emit import write_outputs
from cairn.mcp_server import tools
from cairn.model.graph import Confidence, EdgeType, FactKind
from cairn.paths import cards_dir, workspace_file
from cairn.scan import scan_workspace
from tests.helpers import ctx_for, make_repo, write
from tests.timing import time_limit


def _edges(ws: Path, kind: EdgeType) -> dict[tuple[str, str], Confidence]:
    return {
        (e.source, e.target): e.confidence
        for e in scan_workspace(ws).workspace.edges
        if e.type is kind
    }


# --- C1: a deeply nested compose (or pnpm) file can't crash the process -------------------


def test_deeply_nested_yaml_never_crashes_a_scan(tmp_path: Path) -> None:
    nested = "services: " + "[" * 3000 + "]" * 3000 + "\n"
    write(tmp_path, "evil.py", "")  # keep a module-free script below
    make_repo(
        tmp_path / "ws",
        "infra",
        {"docker-compose.yml": nested, "pnpm-workspace.yaml": "packages: " + "[" * 3000},
    )
    script = (
        "import sys; from pathlib import Path; from cairn.scan import scan_workspace;"
        f"r = scan_workspace(Path(r'{tmp_path / 'ws'}')); print('ok', len(r.workspace.repos))"
    )
    done = subprocess.run(
        [sys.executable, "-c", script], capture_output=True, text=True, timeout=120
    )
    assert done.returncode == 0 and "ok 1" in done.stdout, done.stderr[-500:]


# --- C2: two monorepos with the same internal package names never link -------------------


def test_internal_workspace_packages_never_link_unrelated_monorepos(tmp_path: Path) -> None:
    for repo in ("shop-mono", "blog-mono"):
        root = make_repo(
            tmp_path, repo, {"package.json": json.dumps({"name": repo, "private": True})}
        )
        write(root, "pnpm-workspace.yaml", "packages:\n  - packages/*\n  - apps/*\n")
        write(root, "packages/ui/package.json", json.dumps({"name": "@repo/ui"}))
        write(
            root,
            "apps/web/package.json",
            json.dumps({"name": "web", "dependencies": {"@repo/ui": "workspace:*"}}),
        )
    assert _edges(tmp_path, EdgeType.DEPENDS_ON_PACKAGE) == {}


# --- I1, I2: compose anchors and workspace globs stay bounded ------------------------------


def test_compose_anchor_bombs_are_bounded(tmp_path: Path) -> None:
    deps = "".join(f"      - s{i}\n" for i in range(3000))
    services = "".join(f"  s{i}: *base\n" for i in range(3000))
    text = f"x-base: &base\n  build: ../app\n  depends_on:\n{deps}services:\n{services}"
    repo = make_repo(tmp_path, "infra", {"docker-compose.yml": text[:250_000]})
    start = time.perf_counter()
    InfraDetector().run(ctx_for(tmp_path, repo))
    assert time.perf_counter() - start < time_limit(1.5)


def test_workspace_patterns_are_deduplicated_and_budgeted(tmp_path: Path) -> None:
    root = make_repo(tmp_path, "mono", {"package.json": "{}"})
    patterns = "".join(f"  - '{'./' * (i % 5)}**'\n" for i in range(300))
    write(root, "pnpm-workspace.yaml", "packages:\n" + patterns)
    for i in range(40):
        for j in range(40):
            (root / f"d{i}" / f"e{j}").mkdir(parents=True)
    start = time.perf_counter()
    workspace_packages(root)
    assert time.perf_counter() - start < time_limit(2.0)


# --- I3 + M2: generated gRPC code and generic service names -------------------------------


def test_generated_grpc_code_and_generic_services_make_no_false_links(tmp_path: Path) -> None:
    generated = "// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\nfunc RegisterTripsServiceServer(s, srv) {}\nfunc NewTripsServiceClient(cc) {}\n"
    make_repo(
        tmp_path,
        "trips-svc",
        {"pb/trips_grpc.pb.go": generated, "main.go": "pb.RegisterTripsServiceServer(s, &srv{})"},
    )
    make_repo(
        tmp_path,
        "gateway",
        {"pb/trips_grpc.pb.go": generated, "client.go": "c := pb.NewTripsServiceClient(conn)"},
    )
    make_repo(
        tmp_path,
        "protos",
        {
            "gen/trips_pb2_grpc.py": "class TripsServiceStub(object):\n    pass\ndef add_TripsServiceServicer_to_server(s, srv):\n    pass\n"
        },
    )
    make_repo(
        tmp_path,
        "chain",
        {"app.go": "types.RegisterQueryServer(s, k)\nhealth.RegisterHealthServer(s, h)"},
    )
    make_repo(
        tmp_path, "web", {"q.ts": "const qc = new QueryClient()\nconst h = new HealthClient(addr)"}
    )
    assert _edges(tmp_path, EdgeType.GRPC) == {("gateway", "trips-svc"): Confidence.INFERRED}


# --- I4 + M1: hints must name exactly the target ------------------------------------------


def test_company_prefix_in_hint_doesnt_promote_and_named_absent_owner_is_not_inferred(
    tmp_path: Path,
) -> None:
    make_repo(
        tmp_path,
        "acme-trips",
        {"package.json": json.dumps({"name": "@acme/trips"}), "s.js": "app.get('/invoices', h)"},
    )
    make_repo(tmp_path, "acme-billing", {"package.json": json.dumps({"name": "@acme/billing"})})
    make_repo(tmp_path, "gateway", {"g.ts": "fetch(`${process.env.ACME_BILLING_URL}/invoices`)"})
    edges = _edges(tmp_path, EdgeType.CALLS_HTTP)
    assert edges.get(("gateway", "acme-trips")) in (None, Confidence.AMBIGUOUS)


def test_a_gateway_proxying_its_own_route_still_links_to_the_named_service(tmp_path: Path) -> None:
    make_repo(tmp_path, "trips-svc", {"main.py": '@app.get("/trips/{trip_id}")\ndef t(): ...'})
    make_repo(
        tmp_path,
        "gateway",
        {
            "s.js": "app.get('/trips/:id', async (req, res) => res.json(await fetch(`${process.env.TRIPS_SVC_URL}/trips/${req.params.id}`)))"
        },
    )
    assert _edges(tmp_path, EdgeType.CALLS_HTTP) == {("gateway", "trips-svc"): Confidence.EXTRACTED}


# --- I5: client calls aren't routes; I6: a copied OpenAPI spec isn't serving ---------------


def test_go_and_js_client_calls_are_not_served_routes(tmp_path: Path) -> None:
    repo = make_repo(
        tmp_path,
        "reporter",
        {
            "r.go": 'resp, _ := client.R().SetResult(&t).Get("/trips/{id}")',
            "c.js": "router.get('/orders')",
        },
    )
    served = {f.value for f in HttpDetector().run(ctx_for(tmp_path, repo)).exposes}
    assert served == set()


def test_frontend_holding_the_backend_openapi_spec_still_links(tmp_path: Path) -> None:
    make_repo(tmp_path, "trips-api", {"main.py": '@app.get("/trips/{trip_id}")\ndef t(): ...'})
    make_repo(
        tmp_path,
        "web",
        {
            "openapi.yaml": "paths:\n  /trips/{id}:\n    get: {}\n",
            "t.ts": "fetch(`${process.env.NEXT_PUBLIC_TRIPS_API_URL}/trips/${id}`)",
        },
    )
    assert _edges(tmp_path, EdgeType.CALLS_HTTP) == {("web", "trips-api"): Confidence.EXTRACTED}


# --- I7, I8, M6: monorepo surfaces ----------------------------------------------------------


def _big_monorepo(ws: Path) -> None:
    root = make_repo(
        ws,
        "platform",
        {"package.json": json.dumps({"name": "platform", "scripts": {"dev": "turbo dev"}})},
    )
    write(root, "pnpm-workspace.yaml", "packages:\n  - packages/*\n")
    for i in range(60):
        write(root, f"packages/p{i:02d}/package.json", json.dumps({"name": f"@acme/p{i:02d}"}))
    make_repo(ws, "billing")
    sub = make_repo(ws, "tools-mono", {"go.work": "use ./svc/billing\n"})
    write(sub, "svc/billing/go.mod", "module github.com/acme/billing\n")


def test_packages_are_capped_on_cards_and_runs_survive(tmp_path: Path) -> None:
    _big_monorepo(tmp_path)
    write_outputs(tmp_path, scan_workspace(tmp_path))
    card = (cards_dir(tmp_path) / "platform.md").read_text(encoding="utf-8")
    packages = card.split("## Packages", 1)[1].split("##", 1)[0]
    assert len([line for line in packages.splitlines() if "→" in line]) <= 8
    assert "## Run" in card and "npm run dev" in card


def test_repo_ids_win_over_package_names_and_duplicates_are_listed(tmp_path: Path) -> None:
    _big_monorepo(tmp_path)
    write_outputs(tmp_path, scan_workspace(tmp_path))
    assert tools.resolve_text(tmp_path, "billing").splitlines()[0].startswith("- billing")


def test_package_paths_follow_a_moved_monorepo(tmp_path: Path) -> None:
    # A real git repo, so the per-repo cache is used across the move.
    from cairn.bench.workspace import materialize

    src = tmp_path / "src" / "platform"
    write(src, ".fixture-repo", "")
    write(src, "package.json", "{}")
    write(src, "pnpm-workspace.yaml", "packages:\n  - packages/*\n")
    write(src, "packages/ui/package.json", json.dumps({"name": "@acme/ui"}))
    ws = materialize(tmp_path / "src", tmp_path / "ws")
    scan_workspace(ws)  # fills the cache
    (ws / "services").mkdir()
    (ws / "platform").rename(ws / "services" / "platform")
    repo = scan_workspace(ws).workspace.repo("platform")
    assert repo is not None and repo.packages[0].path == "services/platform/packages/ui"


# --- I9: env reference lines never carry fallback secrets ----------------------------------


def test_env_reference_evidence_never_holds_fallback_values(tmp_path: Path) -> None:
    make_repo(
        tmp_path,
        "a",
        {
            "k.ts": 'const k = process.env.SHARED_SIGNING_TOKEN || "fallback_plainsecretvalue_ZZZ999"'
        },
    )
    write_outputs(tmp_path, scan_workspace(tmp_path))
    assert "fallback_plainsecretvalue" not in workspace_file(tmp_path).read_text(encoding="utf-8")


# --- I10: MCP tool docs list the new kinds --------------------------------------------------


def test_mcp_tool_docs_list_new_kinds(tmp_path: Path) -> None:
    from cairn.mcp_server.server import build_server

    make_repo(tmp_path, "web")
    write_outputs(tmp_path, scan_workspace(tmp_path))
    source = Path(sys.modules[build_server.__module__].__file__ or "").read_text(encoding="utf-8")
    for kind in (
        "calls_http",
        "grpc",
        "pubsub",
        "compose_link",
        "http_route",
        "topic",
        "grpc_service",
    ):
        assert kind in source


# --- M3: websocket/HTTP responses aren't topics ----------------------------------------------


def test_ws_and_res_send_are_not_publishes(tmp_path: Path) -> None:
    from cairn.detectors.messaging import MessagingDetector

    repo = make_repo(
        tmp_path,
        "web",
        {"s.ts": "ws.send('price.update')\nres.send('not-found')\nsocket.send('a.b.c')"},
    )
    topics = [
        f
        for f in MessagingDetector().run(ctx_for(tmp_path, repo)).exposes
        if f.kind is FactKind.TOPIC
    ]
    assert topics == []


# --- M4, M5: compose images and remote build contexts ----------------------------------------


def test_public_images_and_git_contexts_make_no_compose_links(tmp_path: Path) -> None:
    compose = (
        "services:\n  api:\n    build: ../api\n    depends_on: [db, ext]\n"
        "  db:\n    image: postgres:16\n  ext:\n    build: https://github.com/acme/public-api.git#main\n"
    )
    make_repo(tmp_path, "infra", {"docker-compose.yml": compose})
    make_repo(tmp_path, "api")
    make_repo(tmp_path, "postgres")
    make_repo(tmp_path, "public-api")
    assert _edges(tmp_path, EdgeType.COMPOSE_LINK) == {}


@pytest.mark.parametrize("image", ["ghcr.io/acme/api:1.2", "acme/api"])
def test_namespaced_images_still_link(tmp_path: Path, image: str) -> None:
    compose = (
        f"services:\n  web:\n    build: ../web\n    depends_on: [api]\n  api:\n    image: {image}\n"
    )
    make_repo(tmp_path, "infra", {"docker-compose.yml": compose})
    make_repo(tmp_path, "web")
    make_repo(tmp_path, "api")
    assert _edges(tmp_path, EdgeType.COMPOSE_LINK) == {("web", "api"): Confidence.EXTRACTED}
