"""Messaging detector (spec §21.2): gRPC services implemented/called, and pub/sub topics.

A repo *exposes* a gRPC service it implements and a topic it publishes; it *consumes* a service
it constructs a client for and a topic it subscribes to. Topic names must look specific
(`trip.completed`, not `events`). Line-based and bounded.
"""

import re
from pathlib import Path, PurePosixPath

from cairn.detectors.base import DetectorContext, DetectorResult, merge_facts
from cairn.detectors.database import MAX_FACTS_PER_FILE
from cairn.model.graph import Fact, FactKind

_SUFFIXES = frozenset({".go", ".py", ".ts", ".tsx", ".js", ".mjs", ".cjs", ".java", ".kt", ".cs"})
_LINE_MAX = 2000
_N = r"(\w{1,80})"
_T = r"""['"]([^'"\s]{3,120})['"]"""

_GRPC_SERVE = tuple(
    re.compile(p)
    for p in (
        rf"\bRegister{_N}Server\(",
        rf"\badd_{_N}Servicer_to_server\(",
        rf"\bclass\s+\w+\(\s*(?:\w+\.)*{_N}Servicer\s*\)",
        rf"\b{_N}Grpc\.\w{{1,80}}ImplBase\b",
        rf"\baddService\(\s*(?:\w+\.)*{_N}\.service\s*,",
        rf"\baddService\(\s*{_N}\s*,",
    )
)
_GRPC_CALL = tuple(
    re.compile(p)
    for p in (
        rf"\bNew{_N}Client\(",
        rf"\b{_N}Stub\(",
        rf"\bnew\s+{_N}Client\(",
        rf"\b{_N}Grpc\.new(?:Blocking|Future)?Stub\(",
    )
)
_PUBLISH = tuple(
    re.compile(p)
    for p in (
        rf"(\w+)\.(?:send|produce|publish|Publish|send_and_wait|sendMessage|convertAndSend)\(\s*{_T}",
        rf"(\w+)\.(?:send|produce)\(\s*\{{[^}}\n]{{0,200}}?topic\s*:\s*{_T}",
    )
)
# subscribe(['a', 'b']) lists several quoted topics; the other forms name one.
_SUBSCRIBE_LIST = re.compile(
    r"""\.(?:subscribe|Subscribe|QueueSubscribe)\(\s*\[?\s*((?:['"][^'"\n]{0,120}['"]\s*,?\s*){1,20})"""
)
_SUBSCRIBE = tuple(
    re.compile(p)
    for p in (
        rf"\.subscribe\(\s*\{{[^}}\n]{{0,200}}?topics?\s*:\s*\[?\s*{_T}",
        rf"@KafkaListener\([^)\n]{{0,200}}?topics\s*=\s*\{{?\s*{_T}",
        rf"\bKafkaConsumer\(\s*{_T}",
        rf"@RabbitListener\([^)\n]{{0,200}}?queues\s*=\s*\{{?\s*{_T}",
        rf"\.setQueueNames\(\s*{_T}",
    )
)
# Spring AMQP consumers often name their queue in a field the listener container reads
# (`queueName = "shipping-task"`). That counts only in a file that declares a listener: the
# publishing side usually declares the same queue too.
_LISTENER_MARKERS = ("MessageListener", "RabbitListener", "SimpleMessageListenerContainer")
_QUEUE_FIELD = re.compile(rf"\bqueue\w{{0,30}}\s*=\s*{_T}")
_QUOTED = re.compile(r"""['"]([^'"\s]{3,120})['"]""")
# Every pattern above needs one of these substrings; a line with none can't match any of them.
_GATE = (
    "Server(",
    "Servicer",
    "ImplBase",
    "addService(",
    "Client(",
    "Stub(",
    "send",
    "produce",
    "ublish",
    "ubscribe",
    "KafkaListener",
    "KafkaConsumer(",
    "RabbitListener",
    "setQueueNames",
    "queue",
    "convertAndSend",  # its "Send" is capitalised: "send" above doesn't cover it
)
# Generated stubs define both sides of every service; they say nothing about who calls whom.
_GENERATED_SUFFIXES = (
    ".pb.go",
    "_pb2_grpc.py",
    "_pb2.py",
    "_grpc_pb.js",
    "_grpc_pb.ts",
    "_pb.ts",
    "_pb.js",
)
_GENERATED_MARKERS = (
    "code generated",
    "do not edit",
    "@generated",
    "generated by the protocol buffer",
)
# Framework services every app has (health checks, reflection, Cosmos-style Query/Msg).
_GENERIC_SERVICES = frozenset(
    {"Health", "Query", "Msg", "ServerReflection", "Reflection", "Service", "Admin"}
)
# `.send()` on these is a WebSocket or an HTTP response, not a message broker.
_NOT_BROKERS = frozenset(
    {
        "ws",
        "websocket",
        "socket",
        "sock",
        "res",
        "response",
        "reply",
        "req",
        "request",
        "io",
        "window",
        "win",
        "port",
        "worker",
        "self",
        "this",
        "conn",
        "connection",
        "peer",
        "client_socket",
    }
)
_VAGUE_TOPICS = frozenset({"events", "messages", "default", "topic", "queue", "updates", "jobs"})
_NOT_TOPICS = ("text/", "application/", "image/", "multipart/", "http:", "https:", "/")


class MessagingDetector:
    id = "messaging"

    def run(self, ctx: DetectorContext) -> DetectorResult:
        exposes: list[Fact] = []
        consumes: list[Fact] = []
        for path in ctx.files(_wanted):
            text = ctx.read(path)
            if text and not _generated(text):
                found_exposes, found_consumes = _scan(ctx, path, text)
                exposes += found_exposes
                consumes += found_consumes
        return DetectorResult(exposes=merge_facts(exposes), consumes=merge_facts(consumes))


def _scan(ctx: DetectorContext, path: Path, text: str) -> tuple[list[Fact], list[Fact]]:
    exposes: list[Fact] = []
    consumes: list[Fact] = []
    if not any(key in text for key in _GATE):
        return exposes, consumes
    listener = any(marker in text for marker in _LISTENER_MARKERS)
    for line_no, raw in enumerate(text.splitlines(), start=1):
        if len(exposes) + len(consumes) >= MAX_FACTS_PER_FILE:
            break
        line = raw[:_LINE_MAX]
        if not any(key in line for key in _GATE):
            continue
        definition = line.lstrip().startswith(("func ", "def ", "class ", "export function "))
        implements = line.lstrip().startswith("class ") and "Servicer" in line
        served = (
            []
            if definition and not implements
            else [_service(m.group(1)) for p in _GRPC_SERVE for m in p.finditer(line)]
        )
        called = (
            []
            if definition
            else [_service(m.group(1)) for p in _GRPC_CALL for m in p.finditer(line)]
        )
        served = [s for s in served if s not in _GENERIC_SERVICES]
        called = [s for s in called if s not in _GENERIC_SERVICES]
        published = [
            m.group(2)
            for p in _PUBLISH
            for m in p.finditer(line)
            if m.group(1).lower() not in _NOT_BROKERS
        ]
        subscribed = [
            t for m in _SUBSCRIBE_LIST.finditer(line) for t in _QUOTED.findall(m.group(1))
        ]
        subscribed += [m.group(1) for p in _SUBSCRIBE for m in p.finditer(line)]
        if listener:
            subscribed += [m.group(1) for m in _QUEUE_FIELD.finditer(line)]
        if not (served or called or published or subscribed):
            continue
        evidence = (ctx.evidence(path, line_no, line),)
        exposes += [Fact(kind=FactKind.GRPC_SERVICE, value=v, evidence=evidence) for v in served]
        consumes += [Fact(kind=FactKind.GRPC_SERVICE, value=v, evidence=evidence) for v in called]
        exposes += [
            Fact(kind=FactKind.TOPIC, value=t, evidence=evidence) for t in published if _topic(t)
        ]
        consumes += [
            Fact(kind=FactKind.TOPIC, value=t, evidence=evidence) for t in subscribed if _topic(t)
        ]
    return exposes, consumes


def _wanted(name: str) -> bool:
    lowered = name.lower()
    return PurePosixPath(lowered).suffix in _SUFFIXES and not lowered.endswith(_GENERATED_SUFFIXES)


def _generated(text: str) -> bool:
    head = "\n".join(text.splitlines()[:5]).lower()
    return any(marker in head for marker in _GENERATED_MARKERS)


def _service(name: str) -> str:
    """grpc-tools names TS services `XServiceService`; every other generator says `XService`."""
    return name[: -len("Service")] if name.endswith("ServiceService") else name


def _topic(name: str) -> bool:
    lowered = name.lower()
    return (
        len(name) >= 5
        and any(ch in name for ch in ".-_/:")
        and lowered not in _VAGUE_TOPICS
        and not lowered.startswith(_NOT_TOPICS)
    )
